version: '3'

services:
  app_crawler:
    container_name: crawler_app
    build:
      context: ./
      dockerfile: Dockerfile-up
    command: python main.py
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - MONGO_URI=mongo:27017
      - MONGO_PASSWORD_MLAB=!products_db_user2019
      - MONGO_USER_MLAB=products_db_user
      - MONGO_DATABE=products_db